# первое задание
number1 = int(input('введите целое число'))
number2 = int(input('введите второе целое число'))
line1 = str(input('введите текст'))
number3 = float(input('введите дробное число'))
print(number1, number2, line1, number3)
# вторе задание
number1 = int(1)
number2 = float(1.1)
logics1 = bool(1)
line1 = str('один')
number11 = str(number1)
number21 = str(number2)
logics11 = str(logics1)
print(type(number11), type(number21), type(logics11))
# третье задание
name = input('введите имя')
patronymic = input('введите отчество')
surname = input('введите фамилию')
age = input('сколько вам лет')
city = input('из какого вы города')
print(surname, name, patronymic)
print(age)
print(city)
